export const SYNC_HEADER_INT_COUNT = 2
export const SYNC_STATUS_INDEX = 0
export const SYNC_LENGTH_INDEX = 1
export const SYNC_HEADER_BYTES =
	SYNC_HEADER_INT_COUNT * Int32Array.BYTES_PER_ELEMENT
export const SYNC_PAYLOAD_BYTES = 64 * 1024
export const SYNC_TOTAL_BYTES = SYNC_HEADER_BYTES + SYNC_PAYLOAD_BYTES
export const SYNC_STATUS_PENDING = 0
export const SYNC_STATUS_READY = 1
export const SYNC_STATUS_OVERFLOW = 2
